export const products = [
	{
		tag: 'Digital Course',
		tagLight: true,
		image: 'linear-gradient(135deg,#EFE7DC 0%,#DCCFBB 100%)',
		title: 'Mastering Light & Shadow',
		desc: 'Comprehensive video course on studio lighting setups for product photography.',
		metricLabel: 'REVENUE',
		metric: '$12,450',
		countLabel: 'SALES',
		count: '142',
	},
	{
		tag: 'Digital Download',
		tagLight: false,
		image: 'linear-gradient(135deg,#151A22 0%,#1F2A38 100%)',
		title: 'Cinematic LUTs Vol 1',
		desc: 'A pack of 20 color grading presets for Premiere Pro and DaVinci Resolve.',
		metricLabel: 'REVENUE',
		metric: '$8,900',
		countLabel: 'SALES',
		count: '356',
	},
	{
		tag: '1:1 Service',
		tagLight: true,
		image: 'linear-gradient(135deg,#E7EDE8 0%,#CFD9D2 100%)',
		title: 'Portfolio Review Session',
		desc: 'A 60-minute personalized video call reviewing your design portfolio.',
		metricLabel: 'REVENUE',
		metric: '$4,500',
		countLabel: 'BOOKINGS',
		count: '18',
	},
];
