export const sessionsData = [
  {
    id: 1,
    device: 'Chrome on macOS',
    location: 'San Francisco, USA',
    ip: '192.168.1.1',
    icon: 'Laptop',
    isActive: true,
    lastActive: 'Active now',
    status: 'Active now',
    statusColor: 'green',
  },
  {
    id: 2,
    device: 'Safari on iPhone',
    location: 'San Jose, USA',
    ip: '10.0.0.42',
    icon: 'Smartphone',
    isActive: false,
    lastActive: '2 hours ago',
    status: 'Last active: 2 hours ago',
    statusColor: 'gray',
  },
  {
    id: 3,
    device: 'Firefox on Windows',
    location: 'New York, USA',
    ip: '192.168.1.100',
    icon: 'Monitor',
    isActive: false,
    lastActive: '5 days ago',
    status: 'Last active: 5 days ago',
    statusColor: 'gray',
  },
];