export const transactionSummary = {
  totalVolume: 24592,
  totalOrders: 342,
  refundRate: 1.2,
  volumeGrowth: 12.5,
  orderGrowth: 8.2,
  refundGrowth: 0,
};

export const transactions = [
  {
    id: '#ORD-9482',
    customer: 'Sarah Jenkins',
    email: 'sarah.j@example.com',
    initials: 'SJ',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSFsrPjZ6ldx20HIqJqWKmXIKVrInmmgyLOGT5ToZFILQ&s=10',
    product: 'Advanced Figma Masterclass',
    type: 'Digital Course',
    date: 'Oct 24, 2023',
    time: '14:32 WAT',
    amount: 149000,
    status: 'COMPLETED',
  },
  {
    id: '#ORD-9481',
    customer: 'Marcus Rodriguez',
    email: 'm.rodriguez@tech.io',
    initials: 'MR',
    product: '1-on-1 Portfolio Review',
    type: 'Consultation',
    date: 'Oct 24, 2023',
    time: '11:15 WAT',
    amount: 250000,
    status: 'PENDING',
  },
  {
    id: '#ORD-9479',
    customer: 'David Chen',
    email: 'david.c@designco.com',
    initials: 'DC',
    image: 'https://img.magnific.com/free-photo/portrait-white-man-isolated_53876-40306.jpg?semt=ais_hybrid&w=740&q=80',
    product: 'UI Kit Premium Bundle',
    type: 'Digital Asset',
    date: 'Oct 23, 2023',
    time: '09:45 WAT',
    amount: -89000,
    status: 'REFUNDED',
  },
  {
    id: '#ORD-9478',
    customer: 'Olivia Smith',
    email: 'olivia@example.com',
    initials: 'OS',
    product: 'UX Research Workshop',
    type: 'Workshop',
    date: 'Oct 22, 2023',
    time: '16:20 WAT',
    amount: 320000,
    status: 'COMPLETED',
  },
  {
    id: '#ORD-9477',
    customer: 'James Wilson',
    email: 'james@example.com',
    initials: 'JW',
    image: 'https://images.rawpixel.com/image_png_800/cHJpdmF0ZS9sci9pbWFnZXMvd2Vic2l0ZS8yMDIyLTA4L2pvYjEwMzQtZWxlbWVudC0wNy00MDMucG5n.png',
    product: 'Design System Course',
    type: 'Digital Course',
    date: 'Oct 22, 2023',
    time: '13:10 WAT',
    amount: 180000,
    status: 'COMPLETED',
  },
  {
    id: '#ORD-9476',
    customer: 'Amelia Brown',
    email: 'amelia@example.com',
    initials: 'AB',
    image: 'https://img.magnific.com/free-photo/portrait-white-man-isolated_53876-40306.jpg?semt=ais_hybrid&w=740&q=80',
    product: 'UI Design Consultation',
    type: 'Consultation',
    date: 'Oct 21, 2023',
    time: '10:25 WAT',
    amount: 125000,
    status: 'PENDING',
  },
];